spring:
  application:
    name: persona-personas
  datasource:
    url: jdbc:postgresql://localhost:5432/persona_db
    username: persona_user
    password: secret1234
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: health